### ISSUE TITLE
to_s crash, presumably when doc has word/document22.xml inside

### ISSUE THREAD

**Issue by bmulholland** [ruby-docx/docx#106]
As discussed in https://github.com/ruby-docx/docx/issues/103, one bug led to another.

With [the file referenced in that PR](https://github.com/ruby-docx/docx/files/6416360/weird_docx.docx), a crash occurs when getting the file's text:

Source:
```
    Docx::Document.open(file) do |doc|
      return doc.to_s
    end
```

Trace:
```
     NoMethodError:
       undefined method `xpath' for nil:NilClass
     # /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/docx-0.6.1/lib/docx/document.rb:94:in `hyperlink_relationships'
     # /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/docx-0.6.1/lib/docx/document.rb:88:in `hyperlinks'
     # /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/docx-0.6.1/lib/docx/document.rb:48:in `document_properties'
     # /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/docx-0.6.1/lib/docx/document.rb:189:in `parse_paragraph_from'
     # /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/docx-0.6.1/lib/docx/document.rb:61:in `block in paragraphs'
     # /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/nokogiri-1.11.3-x86_64-darwin/lib/nokogiri/xml/node_set.rb:239:in `block in each'
     # /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/nokogiri-1.11.3-x86_64-darwin/lib/nokogiri/xml/node_set.rb:238:in `upto'
     # /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/nokogiri-1.11.3-x86_64-darwin/lib/nokogiri/xml/node_set.rb:238:in `each'
     # /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/docx-0.6.1/lib/docx/document.rb:61:in `map'
     # /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/docx-0.6.1/lib/docx/document.rb:61:in `paragraphs'
     # /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/docx-0.6.1/lib/docx/document.rb:110:in `to_s'
```

**Comment by satoryu** [comment]
Hi, @bmulholland 

I fixed this bug and released new version of docx gem :tada: 
Please try it and give us your feedback!

- [docx | RubyGems.org | your community gem host](https://rubygems.org/gems/docx/versions/0.6.2)

**Comment by bmulholland** [comment]
Confirmed fixed - thank you!
